services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.application
    container_name: idyie-api-application
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - idyie-network
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  mariadb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.mariadb
    container_name: idyie-api-mariadb
    env_file: .env
    networks:
      - idyie-network
    ports:
      - "3307:3306"
    volumes:
      - idyie-api-mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  idyie-network:
    external: true

volumes:
  idyie-api-mariadb:
