FROM mariadb:latest

COPY ./docker/mariadb/*.sql /docker-entrypoint-initdb.d/

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y mariadb-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
