default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  username: root
  password: password
  host: idyie-api-mariadb
  reconnect: true
  connect_timeout: 5
  read_timeout: 5
  write_timeout: 5

development:
  <<: *default
  database: idyie_api_development

test:
  <<: *default
  database: idyie_api_test

production:
  <<: *default
  database: idyie_api_production
