default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: idyie-api-mariadb

development:
  <<: *default
  database: idyie_api_development

test:
  <<: *default
  database: idyie_api_test

production:
  <<: *default
  database: idyie_api_production
