name: Build Docker Images

on:
  workflow_run:
    workflows: ["Lint with RuboCop"]  # Workflow triggered after the `lint.yml` workflow
    types:
      - completed

jobs:
  docker_build:
    name: Build Docker Compose
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build
